title: Zhejian Zhao 
description: My Personal Blog
author: Zhejian Zhao
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/jerryzhao0423
about: Freelance developer

baseurl: "https://jerryzhao0423.github.io"
url: "https://jerryzhao0423.github.io"

allowsearch: true

disqus_shortname: aboutjerry
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
